services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory to /app in the container
      # This allows for live-reloading of code changes
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
